# -*- coding: utf-8 -*-
"""stream-diabetes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sA1QORFBk6UoupcbEKaH2WMZiPQqESE
"""

import pickle

import streamlit as st

import pandas as pd

df = pd.read_csv("diabetes.csv")

df.to_csv("diabetes.csv", index=False)

import pickle

diabetes_model = pickle.load(open('/mount/src/prediksi-diabetes/diabetes_model.sav', 'rb'))

import streamlit as st
st.title('Prediksi Diabetes')

#membagi kolom
col1, col2 = st.columns(2)

with col1 :
    pregnancies = st.text_input ('input nilai Pregnancies')

with col2 :
    Glucose = st.text_input ('input nilai Glucose')

with col1 :
    BloodPressure = st.text_input('input nilai Blood Pressure')

with col2 :
    SkinThickness = st.text_input('input nilai Skin Thickness')

with col1 :
    Insulin = st.text_input('input nilai Insulin')

with col2 :
  BMI = st.text_input('BMI')

with col1 :
  DiabetesPedigreeFunction = st.text_input('input nilai Diabetes Pedigree Function')

with col2 :
  Age = st.text_input('Age')

# code untuk prediksi
diab_diagnosis = ''
# membuat tombol untuk prediksi
if st.button('Test Prediksi Diabetes'):
    diab_prediction = diabetes_model.predict([[pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]])
    if(diab_prediction[0] == 1):
        diab_diagnosis = 'Pasien terkena Diabetes'
    else :
        diab_diagnosis = 'Pasien tidak terkena Diabetes'
    st.success(diab_diagnosis)
